name = "PSASimulator"
uuid = "eab7f6fe-1ad6-4d68-9f3e-0f59499d4d38"
authors = ["Xiangyu Yin"]
version = "0.1.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEqBDF = "6ad6398a-0878-4a85-9266-38940aa047c8"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ADTypes = "1"
LinearAlgebra = "1"
OrdinaryDiffEqBDF = "1.26, 2"
SparseArrays = "1"
Test = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
